# Generated by Django 4.0.5 on 2022-06-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituciones', models.CharField(max_length=20)),
            ],
        ),
    ]
