# Generated by Django 4.0.5 on 2022-06-29 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0002_language'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Language',
            new_name='Institutions',
        ),
    ]
