# Generated by Django 4.0.5 on 2022-06-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0003_rename_language_institutions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutions',
            name='instituciones',
            field=models.CharField(max_length=50),
        ),
    ]
