# Generated by Django 4.0.5 on 2022-06-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0004_alter_institutions_instituciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutions',
            name='instituciones',
            field=models.CharField(max_length=20),
        ),
    ]
