# Generated by Django 4.0.5 on 2022-07-01 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0005_alter_institutions_instituciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigos', models.CharField(max_length=10)),
            ],
        ),
    ]
