# Generated by Django 4.0.5 on 2022-07-02 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0006_cods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cods',
            name='codigos',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='institutions',
            name='instituciones',
            field=models.CharField(default='UNIVERSIDAD FRANCISCO DE PAULA SANTANDER-CUCUTA', max_length=20),
        ),
    ]
